name: Maven Tests

on:
  push:
    branches:
      - dev
      - staging
      - regression
      - production
  pull_request:
    branches:
      - staging
      - regression
      - production

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify your Java version
          distribution: 'temurin'  # Use Temurin (Adoptium) JDK

      - name: Run Maven tests
        run: mvn test  # Run Maven tests
